default_language = "zh"

# The URL the site will be built for
base_url = "https://momentaryrainy.github.io/"

title = "Personal Website"
author = "Shunyu Yang"
description = "Shunyu Yang's personal website"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feeds = true
feed_filenames = [ "atom.xml",]
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    { name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
#highlight_code = false

[extra]
logo_image = "images/logo.svg"
social_media_share_image = "/images/01.jpg"
disqus_identifier = ""
google_analytics = ""
twitter_handle = ""

author_image = '/images/01.jpg'

navigation = [
    { url = "$BASE_URL", title = "主页" },
    { url = "$BASE_URL/tags", title = "项目标签" },
    { url = "$BASE_URL/about", title = "关于我" }
]

social_icons = [
    { url = "https://github.com/MomentaryRainY", icon = "GitHub" },
    #{ url = "https://twitter.com/_cydave", icon = "Twitter" },
    #{ url = "$BASE_URL/atom.xml", icon = "RSS" },
    #{ url = "https://pinterest.com", icon = "Pinterest"},
]
date_format = "%d %b %Y"
language_direction = "auto"
keywords = ["keyword1", "keyword2", "keyword3"]


[extra.footer]
menu = [
    { url = "$BASE_URL", title = "Home" },
    #{ url = "$BASE_URL/projects/", title = "Projects" },
    { url = "$BASE_URL/elements/", title = "Elements" },
    { url = "$BASE_URL/about/", title = "About" },
    # { url = "$BASE_URL/posts/", title = "Blog" },
]
#copyright = ""


[[extra.content_blocks]]
block = "hero"
title = "这里是Momentary Rainy的个人作品网站"
description_html = "游戏见识丰富，见解深刻，在游戏客户端和技术美术方向均有研究的i人"
image = "/images/01.jpg"
image_alt = "picture"
cta_button_link = "about"
cta_button = "关于我"
works_button_link = "#projects"
works_button = "我的作品"


[[extra.content_blocks]]
block = "projects-section"
title = "客户端方向"
section_path = "client/_index.md"
description_html = """
    <p>有Unity项目经验、C# / C++ 基础、卡牌系统实现、UI 交互、状态机系统、资源管理、性能优化均有涉猎</p>"""
link_url = "/client"
show_projects = true
#任务系统、背包系统

[[extra.content_blocks]]
block = "projects-section"
title = "图形学方向"
section_path = "graphic/_index.md"
description_html = """
    <p>渲染管线、图形 API、DX12 / OpenGL / Vulkan、基本Shader/Compute Shader/Hull Shader、性能优化、数学基础、材质/光照/后处理均有涉猎</p>"""
link_url = "/graphic"
show_projects = true

[[extra.content_blocks]]
block = "projects-section"
title = "较为散乱浅薄的各种尝试"
section_path = "other/_index.md"
description_html = """
    <p>2025及以前的尝试包括NeRF论文、B站Games系列、建模教程、渲染教程等等相关的尝试</p>"""
link_url = "/other"
show_projects = true